# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: financial_tracking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x66inancial_tracking.proto\x12\x11\x66inancialtracking\">\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\"8\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\x1b\n\rTransactionId\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xbd\x04\n\x10\x46inancialTracker\x12<\n\x06SignUp\x12\x17.financialtracking.User\x1a\x17.financialtracking.User\"\x00\x12;\n\x05Login\x12\x17.financialtracking.User\x1a\x17.financialtracking.User\"\x00\x12R\n\x0e\x41\x64\x64Transaction\x12\x1e.financialtracking.Transaction\x1a\x1e.financialtracking.Transaction\"\x00\x12U\n\x0fReadTransaction\x12 .financialtracking.TransactionId\x1a\x1e.financialtracking.Transaction\"\x00\x12U\n\x11UpdateTransaction\x12\x1e.financialtracking.Transaction\x1a\x1e.financialtracking.Transaction\"\x00\x12W\n\x11\x44\x65leteTransaction\x12 .financialtracking.TransactionId\x1a\x1e.financialtracking.Transaction\"\x00\x12S\n\x13ReadAllTransactions\x12\x18.financialtracking.Empty\x1a\x1e.financialtracking.Transaction\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'financial_tracking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSACTION']._serialized_start=47
  _globals['_TRANSACTION']._serialized_end=109
  _globals['_USER']._serialized_start=111
  _globals['_USER']._serialized_end=167
  _globals['_TRANSACTIONID']._serialized_start=169
  _globals['_TRANSACTIONID']._serialized_end=196
  _globals['_EMPTY']._serialized_start=198
  _globals['_EMPTY']._serialized_end=205
  _globals['_FINANCIALTRACKER']._serialized_start=208
  _globals['_FINANCIALTRACKER']._serialized_end=781
# @@protoc_insertion_point(module_scope)
